# SPDX-License-Identifier: MIT
name: Build Fonts

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        fonts: ['KokosaMono']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Iosevka
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: v33.3.6
          repository: be5invis/Iosevka
      - name: Checkout Build Plans
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: _build_plans
      - name: Set up Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20
          cache: 'npm'
      - name: Install ttfautohint
        run: sudo apt-get install -y ttfautohint
      - name: Install dependencies
        run: npm install
      - name: Copy build plans
        run: cp _build_plans/private-build-plans.toml private-build-plans.toml
      - name: Build
        run: |
          npm run build -- ttf::${{ matrix.fonts }}
      - name: Build ZIP Packages
        run: |
          zip -j PkgTTF-${{ matrix.fonts }}.zip dist/${{ matrix.fonts }}/TTF/*.ttf
      - name: Upload Artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: PkgTTF-${{ matrix.fonts }}
          path: PkgTTF-${{ matrix.fonts }}.zip
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      - name: Upload
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: "**/*.zip"
          fail_on_unmatched_files: true
